# Learn more about configuring your checkout UI extension:
# https://shopify.dev/docs/api/checkout-ui-extensions/latest/configuration

# The version of APIs your extension will receive. Learn more:
# https://shopify.dev/docs/api/usage/versioning
api_version = "2026-07"

[[extensions]]
name = "ribbit-upsell"
handle = "ribbit-upsell"
type = "ui_extension"
uid = "d6f3b357-98ba-ac52-a79f-74b20991ac74dc36c37b"

# Controls where in Shopify your extension will be injected,
# and the file that contains your extension’s source code. Learn more:
# https://shopify.dev/docs/api/checkout-ui-extensions/latest/extension-targets-overview

[[extensions.targeting]]
module = "./src/Checkout.jsx"
target = "purchase.checkout.block.render"

[[extensions.targeting]]
module = "./src/Checkout.jsx"
target = "purchase.checkout.cart-line-list.render-after"

[[extensions.targeting]]
module = "./src/Checkout.jsx"
target = "purchase.checkout.reductions.render-after"

[extensions.capabilities]
api_access = true
